// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIebLiejWWI6Gv1pRMS61oYIAbh-UJ5is',
    appId: '1:855092966431:web:03bf9852c83462191e112a',
    messagingSenderId: '855092966431',
    projectId: 'flutterfirebasecrudapp-c89c4',
    authDomain: 'flutterfirebasecrudapp-c89c4.firebaseapp.com',
    storageBucket: 'flutterfirebasecrudapp-c89c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU961zZvp4ixujF4orxyRVtrBAEkVxhyk',
    appId: '1:855092966431:android:78127f9910e4d0b71e112a',
    messagingSenderId: '855092966431',
    projectId: 'flutterfirebasecrudapp-c89c4',
    storageBucket: 'flutterfirebasecrudapp-c89c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Z3pq7fcDoqsNxOO_NUQWk-aTWizlgAU',
    appId: '1:855092966431:ios:69d937a1a09993461e112a',
    messagingSenderId: '855092966431',
    projectId: 'flutterfirebasecrudapp-c89c4',
    storageBucket: 'flutterfirebasecrudapp-c89c4.appspot.com',
    iosClientId: '855092966431-jd16j18s2sqi6k7b5nlb6al1vfqodi71.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudApp',
  );
}
